server:
  port: 8761
spring:
  application:
    name: eureka-server
eureka:
  client:
    registerWithEureka: true   #telling the server not to register himself in the service registry
    fetchRegistry: false